name: deepsno
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.12
  - pytorch=2.5
  - pytorch-cuda=12.4
  - scipy=1.14
  - numpy=2.1
  - python-htcondor=24.1
  - hdf5=1.14
  - h5py=3.12
  - highfive
  - jsonargparse=4.33
  - tensorboard=2.18
