# TODO: Need to put in context window size somewhere. Maybe in h5 files.
train:
    device: &device cuda 
    dataset: 
        class_path: src.data.datasets.PositionRecoDataset
        init_args: 
            path: /data/snoplus3/degraw/uniform_electron_energy/train_dset.h5

    batch_size: 200
    val_batch_size: 400
    shuffle: true
    num_epochs: 5
    train_val_split: 0.97

    model: 
        class_path: src.models.position_reco.PositionReco
        init_args:
            n_pmts: 9728 
            d_model: &d_model 64
            nhead: 4
            dim_feedforward: 128
            num_layers: 6
            dropout: 0.1
            hit_time_embedding_dim: 512
    loss_fn:
        class_path: torch.nn.MSELoss
    optimizer_class: torch.optim.Adam
    optimizer_kwargs:
        lr: 1e-5
        betas: [0.9, 0.98]
        eps: 1e-9
    
    scheduler_class: torch.optim.lr_scheduler.OneCycleLR
    scheduler_kwargs: 
        max_lr: 1e-3
        total_steps: 3000

    val_metric_fn:
        class_path: src.metrics.position_reco.ResolutionLoss
    
    val_num_steps: 200

    max_grad_norm: 1

test:
    test_file: "hello world"