train:
    seed: 783
    checkpoint_dir: /data/snoplus3/degraw/uniform_electron_energy/checkpoints/
    device: &device cuda 
    dataset: 
        class_path: &dataset_class_path src.data.datasets.PositionRecoDataset
        init_args: 
            path: &train_path /data/snoplus3/degraw/uniform_electron_energy/train_dset.h5 

    batch_size: 200
    val_batch_size: &val_batch_size 200
    shuffle: true
    num_workers: &num_workers 32
    num_epochs: 5
    train_val_split: 0.98

    optimizer: 
        class_path: torch.optim.Adam
        init_args:
            lr: 1e-5
            betas: [0.9, 0.98]
            eps: 1e-9
    loss_fn:
        class_path: torch.nn.MSELoss
    scheduler: 
        class_path: torch.optim.lr_scheduler.OneCycleLR
        init_args: 
            max_lr: 1e-3
            total_steps: 60000
            # total_steps: 3000 # this did well

    val_loss_fn:
        class_path: src.metrics.position_reco.ResolutionLoss
    val_loss_is_inverted: false
    val_num_steps: 200

    max_grad_norm: 1

predict:
    ckpt: /data/snoplus3/degraw/uniform_electron_energy/checkpoints/2024-12-11_03-24-40/ckpt
    ckpt_config: /data/snoplus3/degraw/uniform_electron_energy/checkpoints/2024-12-11_03-24-40/config.yaml
    output_file: /data/snoplus3/degraw/uniform_electron_energy/checkpoints/2024-12-11_03-24-40/test_results.h5
    device: *device
    dataset: 
        class_path: *dataset_class_path
        init_args:
            path: /data/snoplus3/degraw/uniform_electron_energy/test_dset.h5
    
    batch_size: *val_batch_size
    num_workers: *num_workers

# TODO: Need to put in context window size somewhere. Maybe in h5 files.
model: 
    class_path: src.models.position_reco.PositionReco
    init_args:
        n_pmts: 9728 
        d_model: &d_model 64
        nhead: 4
        dim_feedforward: 128
        num_layers: 6
        dropout: 0.1
        hit_time_embedding_dim: 512
        norm_dict:
            class_path: src.models.position_reco.PositionRecoNorm
            init_args: 
                train_file: *train_path
